### PR TITLE
Let Net::AMQP handle the frame buffer

### PR DESCRIPTION
**Pull request by kraih**
This is a fix for #11. It removes pretty much all custom frame buffer handling (since it would randomly destroy frames) and instead lets `Net::AMQP` deal with as much of the low level bits as possible. I don't see a sane way to salvage `max_buffer_size`, it will have to be completely redesigned from the ground up, and be made testable from the start to avoid these kinds of problems.

### CODE REVIEW

**Comment by kraih** [comment]
On the plus side, `max_buffer_size` does not appear to be documented yet. 😉

**Comment by kraih** [comment]
Performance also seems to have gone up noticeably.

**Comment by christopherraa** [comment]
@SPodjasek Any chance you could review this and (if accepted) cut a new release?

**Comment by kraih** [comment]
This is a pretty serious bug, until it is fixed i would strongly advice against using `Mojo::RabbitMQ::Client`. You might not even notice a problem if there's very few messages coming from your RabbitMQ server. But once there's a traffic spike, the chance of two messages being sent so closely together that they end up in the same buffer is very high. And then your application will just crash because the AMQP frame gets corrupted.

**Pull request merged**
