### PR TITLE
Allow EXTERNAL as well as AMQPLAIN auth

### PR DESCRIPTION
**Pull request by AdamWill**
I'm trying to publish messages from openQA (which uses this
client library) to fedora-messaging (which is a RabbitMQ broker
using EXTERNAL auth), so I kinda need this. The intent here is
that by default we'll try and use either of AMQPLAIN or EXTERNAL
if the server advertises one or both, preferring AMQPLAIN; the
auth_mechanism query param can be used to specify only one or
the other.

Signed-off-by: Adam Williamson <awilliam@redhat.com>

### CODE REVIEW

**Comment by AdamWill** [comment]
Note: I am not 100% sure this makes sense, I am still feeling this stuff out. But I *think* it's OK, at least for cases where all we need to do is set the right value, we don't need to do anything else 'special' to make the external mechanism work...

**Comment by SPodjasek** [comment]
I'm also wondering how to test this properly to be sure that it will not break people things up when released.

**Comment by AdamWill** [comment]
It really shouldn't....it will still use AMQPLAIN by default any time the server claims to support it, and if the server doesn't claim support for it then the client never would've worked anyway.

FWIW, this *does* do the job I need it to do - with this patch I can publish to our AMQP broker (fedora-messaging) which uses EXTERNAL auth, without it I cannot.

**Comment by AdamWill** [comment]
note - *even if the server lists EXTERNAL ahead of AMQPLAIN*, we still use AMQPLAIN by default. I did that on purpose.

**Pull request merged**
